# Prezentacja możliwości pakietu numpy - przykłady zastosowań

In [3]:
import numpy as np

### Tworzenie tablic 1D (wektory)

In [4]:
v= np.array([1,2,3,4,5,6])

In [5]:
v

array([1, 2, 3, 4, 5, 6])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [9]:
np.linspace(0,12,10)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ])

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
a=np.zeros_like(v)

In [12]:
a

array([0, 0, 0, 0, 0, 0])

In [13]:
o=np.ones(4)

In [14]:
o

array([1., 1., 1., 1.])

In [15]:
np.ones_like(v)

array([1, 1, 1, 1, 1, 1])

In [16]:
c=np.full(3,7)

In [17]:
c

array([7, 7, 7])

In [18]:
np.empty(5)

array([0., 1., 2., 3., 4.])

In [19]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [20]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.random.rand(1,5)

array([[0.61297711, 0.50004755, 0.8265196 , 0.99176177, 0.57532385]])

In [22]:
np.random.randn(1,6)

array([[-1.68456544, -0.86265176,  0.10076297,  0.77122554, -0.07892162,
        -0.53533846]])

In [23]:
np.random.choice(v,3)

array([1, 2, 4])

In [24]:
np.repeat(5,6)

array([5, 5, 5, 5, 5, 5])

In [25]:
np.append(v,np.array([100,200,300]))

array([  1,   2,   3,   4,   5,   6, 100, 200, 300])

In [26]:
los=np.random.default_rng()

In [27]:
los.integers(0,10,3)

array([9, 6, 0], dtype=int64)

In [28]:
los.random(3)

array([0.42379382, 0.19666921, 0.90366575])

In [29]:
los.standard_normal(5)

array([ 1.30577534,  0.83496878,  0.62222642,  0.68337589, -0.42464075])

In [30]:
los.normal(5,2,9) #śednia, odch stand , ile

array([6.41472431, 1.14041776, 6.98986106, 7.84578131, 3.78748988,
       4.79384045, 3.25231071, 4.91326371, 9.31114564])

### Informacje o tablicach

In [31]:
type(v)

numpy.ndarray

In [32]:
v.ndim

1

In [33]:
v.shape

(6,)

In [34]:
v.size

6

In [35]:
v.dtype

dtype('int32')

In [36]:
len(v)

6

### Indeksowanie 

In [37]:
wektor=np.arange(1,15)

In [38]:
wektor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
wektor[1]

2

In [40]:
wektor[::2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [41]:
wektor[0:5]

array([1, 2, 3, 4, 5])

In [42]:
wektor[:3]

array([1, 2, 3])

In [43]:
wektor[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
wektor[-1]

14

In [45]:
wektor[-1:]

array([14])

In [46]:
wektor[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [47]:
lista_indeksów=[0,1,10,11]

In [48]:
wektor[lista_indeksów]

array([ 1,  2, 11, 12])

In [49]:
nowy=np.array([1,2,3,4,5])

In [50]:
nowy

array([1, 2, 3, 4, 5])

In [51]:
lista=[True, False, True, False, True]

In [52]:
nowy[lista]

array([1, 3, 5])

In [53]:
lista2=np.array([1,0,1,0,1], dtype=bool)

In [54]:
nowy[lista2]

array([1, 3, 5])

In [55]:
wektor>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [56]:
wektor[wektor>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
wektor[(wektor >5) & (wektor< 10)]

array([6, 7, 8, 9])

In [58]:
np.any(wektor>5)

True

In [59]:
np.all(wektor>5)

False

In [60]:
np.where(wektor>5)

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int64),)

### Operacje arytmetyczne

In [61]:
wektor*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [62]:
a=np.array([1,2,3])

In [63]:
b=np.array([4,5,6])

In [64]:
a+b

array([5, 7, 9])

In [65]:
a-b

array([-3, -3, -3])

In [66]:
a*b

array([ 4, 10, 18])

In [67]:
a/b

array([0.25, 0.4 , 0.5 ])

In [68]:
a * 1.7

array([1.7, 3.4, 5.1])

In [69]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [70]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [71]:
np.max(a)

3

In [72]:
np.min(a)

1

In [73]:
sum(a)

6

In [74]:
np.sort(a)

array([1, 2, 3])

In [75]:
a

array([1, 2, 3])

In [76]:
for element in wektor:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [77]:
a.mean()

2.0

In [78]:
np.mean(a)

2.0

In [79]:
np.add(a,b)

array([5, 7, 9])

In [80]:
a==b

array([False, False, False])

In [81]:
a>b

array([False, False, False])

In [82]:
a.cumsum()

array([1, 3, 6], dtype=int32)

### Tworzenie tablic 2D (macierze)

In [83]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [85]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [86]:
m=np.diag(np.arange(0, 20, 5))

In [87]:
m

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [88]:
dane = np.array([[1, 2,3], [4, 5,6],[7,8,9]])

In [89]:
dane

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
dane.shape

(3, 3)

In [91]:
np.ones_like(dane)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [92]:
np.zeros_like(dane)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [93]:
dane

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

### Indeksowanie

In [95]:
dane

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
dane[(0,0)]

1

In [97]:
dane[(1,0)]

4

In [98]:
dane[(0,1)]

2

In [99]:
dane[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
dane[0,:]

array([1, 2, 3])

In [101]:
dane[:,0]

array([1, 4, 7])

In [102]:
dane[0,:2]

array([1, 2])

In [103]:
dane[2:,2:]

array([[9]])

In [104]:
dane[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [105]:
dane[0,::2]

array([1, 3])

In [106]:
wierszowo=(0,1)

In [107]:
dane[wierszowo]

2

In [108]:
row_idx=[1,2]

In [109]:
dane[row_idx]

array([[4, 5, 6],
       [7, 8, 9]])

In [188]:
dane[np.ix_([0,1],[1,2])]      # wybieramy 0 i 1 wiersz oraz 1 i 2 kolumne

array([[2, 3],
       [5, 6]])

In [191]:
dane[dane % 2 == 0]               # wybranie elementow o wartosciach parzystych

array([2, 4, 6, 8])

In [110]:
dane[dane>2]

array([3, 4, 5, 6, 7, 8, 9])

In [190]:
np.nonzero(dane == 2) # numery indeksow ktorych elementy maja wartosc 5

(array([0], dtype=int64), array([1], dtype=int64))

### Zmiana kształtu i rozmiaru

In [111]:
x = np.arange(9).reshape((3,3))

In [112]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
d = np.array([[1, 2], [3, 4]])

In [114]:
np.reshape(d, (1, 4))

array([[1, 2, 3, 4]])

In [115]:
d.reshape(4)

array([1, 2, 3, 4])

In [116]:
d.flatten()

array([1, 2, 3, 4])

In [117]:
e = np.arange(0, 5)

In [118]:
kolumnowo = e[:, np.newaxis]

In [119]:
kolumnowo

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [120]:
wierszowo = e[np.newaxis, :]

In [121]:
wierszowo

array([[0, 1, 2, 3, 4]])

In [122]:
np.vstack((e, e, e))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [123]:
np.hstack((e, e, e))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

### Operacje arytmetyczne

In [124]:
a = np.array([[1, 2], [3, 4]]) 

In [125]:
b = np.array([[5, 6], [7, 8]]) 

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
b

array([[5, 6],
       [7, 8]])

In [128]:
a+b

array([[ 6,  8],
       [10, 12]])

In [170]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [129]:
a-b

array([[-4, -4],
       [-4, -4]])

In [169]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [130]:
a*b

array([[ 5, 12],
       [21, 32]])

In [131]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [171]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [132]:
a*2

array([[2, 4],
       [6, 8]])

In [133]:
b**2

array([[25, 36],
       [49, 64]], dtype=int32)

In [161]:
c=np.arange(2,4)

In [162]:
c

array([2, 3])

In [163]:
a.sum()

10

In [164]:
a*c

array([[ 2,  6],
       [ 6, 12]])

In [172]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [136]:
np.sum(a)

10

In [137]:
np.sum(a, axis=0)

array([4, 6])

In [138]:
np.sum(a, axis=1)

array([3, 7])

In [173]:
np.cumsum(a, axis=0)

array([[1, 2],
       [4, 6]], dtype=int32)

In [186]:
np.cumsum(a)

array([ 1,  3,  6, 10], dtype=int32)

In [185]:
np.prod(a) #iloczyn wszystkich elementów

24

In [187]:
np.max(a)

4

In [139]:
dane

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
dane.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Operacje na zbiorach

In [141]:
x = np.arange(0,6)

In [142]:
y=np.arange(1,9)

In [143]:
x

array([0, 1, 2, 3, 4, 5])

In [144]:
y

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
1 in x

True

In [146]:
1 in y

True

In [147]:
8 in x

False

In [148]:
np.union1d(x, y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [149]:
np.intersect1d(x, y)

array([1, 2, 3, 4, 5])

In [150]:
np.setdiff1d(x, y)

array([0])

In [151]:
np.setdiff1d(y, x)

array([6, 7, 8])

### Operacje macierzowe

In [152]:
macierz1 = np.arange(1, 7).reshape(2, 3)

In [153]:
macierz1

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
macierz2 = np.arange(1, 7).reshape(3, 2)

In [155]:
macierz2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [156]:
np.dot(macierz1, macierz2)

array([[22, 28],
       [49, 64]])

In [157]:
np.dot(macierz2, macierz1)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [181]:
macierz1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [182]:
np.transpose(macierz1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [192]:
#  na przekątnej macierzy.
macierz1.diagonal()

array([1, 5])

In [193]:
macierz1.trace() #ślad 

6

In [196]:
matrix = np.array([[1, 4],
                   [2, 5]])

In [197]:
np.linalg.inv(matrix) #odwrotna

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

### cdn...